version: 2.1

jobs:
  webDeterminism:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          command: echo "web service returned 200!"

workflows:
  webokay:
    jobs:
      - webDeterminism
